GET http://localhost:8080/contacts
# GET http://localhost:8080/contacts/6483a9ee0246aff2ba0bc8f6

POST http://localhost:8080/contacts HTTP/1.1
content-type: application/json

{
    "firstName": "Ashlyn",
    "lastName": "Daines",
    "email": "ashlyndaines@test.com",
    "favColor": "Blue",
    "birthday": "06/19/2000"
}

PUT http://localhost:8080/contacts/6483a9ee0246aff2ba0bc8f6 HTTP/1.1
content-type: application/json

{
"firstName":"Kenna", "lastName":"Monty", "email":"monty@gmail.com", "favColor":"Black", "birthday":"April 3, 2001"
} 

DELETE http://localhost:8080/contacts/648adf1c364b132c8afc5c1b HTTP/1.1